AllisonLin8/twitter-api-2020

seeders/20230605150811-users-seed-file.js
seeders/20230605165733-tweets-seed-file.js
seeders/20230606011048-replies-seed-file.js

feat:create seeders

---

seeders/20230605150811-users-seed-file.js

fix: user-seeders

---

migrations/20190115071421-create-user.js
models/user.js

feat: fix user model

---

Procfile
config/config.json

feat: modify config for heroku

---

models/followship.js
models/like.js
models/reply.js
models/tweet.js
models/user.js

fix: modify models

---

config/passport.js
middleware/auth.js
services/user-services.js

fix: signup & error message

---

services/user-services.js

fix: signUp error message

---

services/user-services.js

feat: add confirmPassword msg

---

helper.js/dayjs-helpers.js
models/tweet.js
routes/index.js
services/user-services.js

refactory: user-service

---

controllers/admin-controller.js
routes/index.js
services/admin-services.js
services/user-services.js

新增admin登入API。
1. 已完成所有本地的test。
2. 已在本地POSTMAN測試此API資料有正確回傳。

feat: add admin login api

---

controllers/reply-controller.js
routes/index.js

新增使用者在個別推文中可以看到所有留言的功能
新增使用者可以增加留言的功能

feat:add reply function

---

config/passport.js
helpers/file-helpers.js
helpers/getUserData.js
models/tweet.js
models/user.js
services/tweet-services.js
services/user-services.js

修正使用者按下喜歡後，Tweet相關路由的回傳資料中，會有重複同一筆推文資料的問題。
1. models test : Like未通過。
2. POSTMAN測試已有正確回傳值。

Fix tweet like

---

helpers/file-helpers.js
services/user-services.js

修改使用者資料API：新增修改帳號和密碼。
1. models test全部通過。
2. requests test ：現有功能全部通過。
3. POSTMAN已測試該API有回傳正確資料。

feat: add edit account & password

---

controllers/user-controller.js
models/followship.js
routes/index.js
services/tweet-services.js
services/user-services.js

新增：瀏覽某一使用者正在跟隨的人 & 瀏覽某一使用者有哪些人在關注。
1. 本地測試檔已跑過。
2. POSTMAN回傳值：待種子資料更新後複查。

Get user followers and followings

---

controllers/user-controller.js
routes/index.js
services/tweet-services.js
services/user-services.js

新增：瀏覽某一使用者回覆過的所有推文。
1. 本地測試檔已跑過。
2. POSTMAN檢查回傳值正常。

feat: add getUserReliedTweets api

---

controllers/user-controller.js
routes/index.js
services/tweet-services.js
services/user-services.js

新增：瀏覽某一使用者按讚的所有推文。
1. 本地測試檔已跑過。
2. POSTMAN檢查回傳值正常。

Get user liked tweets

---

controllers/admin-controller.js
package-lock.json
package.json
routes/index.js

feat: add del tweet function

---

controllers/followship-controller.js
controllers/tweet-controller.js
routes/index.js
services/tweet-services.js

尚未完成，
加上dataValues仍無法render出物件

adding followship function(not finished)

---

package.json
routes/index.js

fix: debug heroku error(H10)

---

app.js

fix: modify cors require in app.js

---

controllers/followship-controller.js
models/followship.js
models/like.js
models/reply.js
models/tweet.js
models/user.js

修正followship功能。
1. 本地測試已通過。
2. POSTMAN已確認有正確回傳值。

fix: addFollowing API

---

controllers/followship-controller.js
models/tweet.js
models/user.js
routes/index.js

新增adminGetTweets api。
1. 本地測試已通過。
2. POSTMAN有正確回傳值。

feat: add adminGetTweets api

---

controllers/followship-controller.js
controllers/reply-controller.js
controllers/tweet-controller.js
controllers/user-controller.js
seeders/20230605150811-users-seed-file.js
seeders/20230605165733-tweets-seed-file.js
seeders/20230606011048-replies-seed-file.js
services/tweet-services.js

style: review the message

---

controllers/reply-controller.js
package-lock.json
package.json
services/followship-services.js
services/reply-services.js
services/tweet-services.js

fix: debug

---

middleware/cors.js
routes/index.js
seeders/20230606011048-replies-seed-file.js
seeders/20230611140259-likes-seed-file.js
seeders/20230611140332-followships-seed-file.js
services/followship-services.js
services/reply-services.js

1. 修復3條路由並驗證功能
2. 增加like & followship 種子資料

feat: debug & generate like & followships seed file

---

services/user-services.js

在getUser api的回傳值中新增isFollowed資料。
1. 已通過所有本地測試。

feat: add isFollowed in getUser api

---

.travis.yml

feat: update NODE_ENV

---

routes/index.js
services/reply-services.js
services/tweet-services.js
services/user-services.js

feat: format createdAt

---

services/user-services.js

在回傳值需要isLiked & isFollowed欄位的地方加上。

feat: add isLiked & isFollowed

---

seeders/20230605165733-tweets-seed-file.js
services/reply-services.js

修改回覆及推文種子資料以符合acceptamce critiria

Tweet seed modify

---

controllers/admin-controller.js
routes/index.js
services/admin-services.js
services/followship-services.js
services/tweet-services.js

Debug admin users

---

services/followship-services.js
services/reply-services.js
services/tweet-services.js

Add error message

---

services/followship-services.js
services/user-services.js

fix: debug user follow function

---

seeders/20230611140259-likes-seed-file.js
seeders/20230611140332-followships-seed-file.js
services/reply-services.js

修正like & followship 種子資料重複問題以及postReply的反查bug

fix: seeders & postrely bug

---

services/tweet-services.js
services/user-services.js

修正tweets字數限制bug
更新topusers字數限制

fix: debug tweets & adding substring top user

---

services/tweet-services.js

fix: add & remove like bug

---

services/user-services.js

限縮推文描述的長度，以防前端畫面跑版。
1. 本地測試皆通過。
2. POSTMAN已檢查修改的回傳值是正確的。

feat: change desc length

---

helpers/dayjs-helpers.js
services/tweet-services.js

fix: change the getTweet time

---

services/tweet-services.js
services/user-services.js

新增 coutdown 欄位
修改 comment substring

fix: the comment substring & add countdown

---

services/tweet-services.js

fix : debug the time problem

---

seeders/20230605150811-users-seed-file.js
seeders/20230605165733-tweets-seed-file.js
services/tweet-services.js

修正：個別推文isLiked判斷邏輯問題
修改： user種子資料

Fix get tweet isLiked problem & modify user seeder

---

services/reply-services.js
services/tweet-services.js

修復getTweet可能造成前端無法顯示畫面的問題
修復replyTweet可能造成前端無法顯示畫面的問題

fix: getTweet & replyTweet

---

services/reply-services.js
services/tweet-services.js

fix: delete the password of reply

---

seeders/20230605165733-tweets-seed-file.js
seeders/20230606011048-replies-seed-file.js
seeders/20230611140259-likes-seed-file.js
seeders/20230611140332-followships-seed-file.js
services/reply-services.js

Seeders modify

---

services/user-services.js

fix: let root not appears on topUser page

---

services/user-services.js

fix: delete users sensitive information

---

README.md

doc:modify README file

---

services/admin-services.js

修正likesCount 計數邏輯，針對使用者所有推文被like的數量做統計

Fix likes count

---

services/admin-services.js
services/user-services.js

fix: AdminGetTweets & putUser

---

services/user-services.js

fix: password probelm
